

const FETCH_NETFLIX_ORIGINALS = 'FETCH_NETFLIX_ORIGINALS';
const FETCH_NETFLIX_ORIGINALS_SUCCESS = 'FETCH_NETFLIX_ORIGINALS_SUCCESS';
const FETCH_NETFLIX_ORIGINALS_FAILURE = 'FETCH_NETFLIX_ORIGINALS_FAILURE';

const FETCH_TRENDING = 'FETCH_TRENDING';
const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

const FETCH_TOP_RATED = 'FETCH_TOP_RATED';
const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
const FETCH_TOP_RATED_FAILURE = 'FETCH_TOP_RATED_FAILURE';

const FETCH_ACTION = 'FETCH_ACTION';  
const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS';  
const FETCH_ACTION_FAILURE = 'FETCH_ACTION_FAILURE';  

const FETCH_COMEDY = 'FETCH_COMEDY';
const FETCH_COMEDY_SUCCESS = 'FETCH_COMEDY_SUCCESS';
const FETCH_COMEDY_FAILURE = 'FETCH_COMEDY_FAILURE';

const FETCH_HORROR = 'FETCH_HORROR';
const FETCH_HORROR_SUCCESS = 'FETCH_HORROR_SUCCESS';
const FETCH_HORROR_FAILURE = 'FETCH_HORROR_FAILURE';

const FETCH_ROMANCE = 'FETCH_ROMANCE';  
const FETCH_ROMANCE_SUCCESS = 'FETCH_ROMANCE_SUCCESS';  
const FETCH_ROMANCE_FAILURE = 'FETCH_ROMANCE_FAILURE';  

const FETCH_DOCUMENTARIES = 'FETCH_DOCUMENTARIES';
const FETCH_DOCUMENTARIES_SUCCESS = 'FETCH_DOCUMENTARIES_SUCCESS';
const FETCH_DOCUMENTARIES_FAILURE = 'FETCH_DOCUMENTARIES_FAILURE';
